% my_classification = Classify_with_DT_func(TESTING_DATA, ...
%                       1:size(TRAINING_DATA,1), ...
%                       SHAPELET_IDS, ...
%                       SHAPELETS,...
%                       TREE_NODES, ...
%                       1, ...
%                       zeros(size(TRAINING_DATA,1),1));

my_classification = Classify_with_DT_func(TRAINING_DATA, ...
                      1:size(TRAINING_DATA,1), ...
                      SHAPELET_IDS, ...
                      SHAPELETS,...
                      TREE_NODES, ...
                      1, ...
                      zeros(size(TRAINING_DATA,1),1));